calendar_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import signup
from . import views

app_name = 'calendar_app'


urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name = 'calendar_app/login.html'),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(),name = 'logout'),
    path('signin/',signup.Signin,name = 'signin'),
    path('',views.Eventdisplay,name = 'eventlist'),
    path('createevent/',views.CreateEvent, name = "createevent"),
    path('eventdetail/<int:pk>/',views.EventInfo, name='eventinfo'),
    path('updateevent/<int:pk>/', views.UpdateEvent, name = 'updateevent'),
    path('delete_event/<int:pk>/', views.DeleteEvent, name = 'deleteevent'),
    path('joinevent/<int:pk>/', views.JoinEvent, name = 'joinevent'),
    path('leaveevent/<int:pk>/', views.LeaveEvent, name = 'leaveevent'),
    path('kick_out/<int:event_pk>/<int:pk>/', views.Kick_out, name = 'kick_out'),
    path('memberprofile/<int:pk>/', views.Memberprofile, name = 'memberprofile'), 
    
]

calendar_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import ProfileinfoView
from django.contrib.auth import views as auth_views
from . import views
from calendar_app import signup

urlpatterns = [
    path('',views.Home,name = 'HOME'),
    path('index/',views.Index,name = 'view'),
    path('visitevent/<int:pk>/', views.VisitEvent, name = 'visitevent'),
    #use of as_view() only when you are using any class in views.py else use it normally
    path('thanks/',views.ThanksView.as_view(),name = 'THANKS'),
    path('admin/', admin.site.urls),
    path('profiledetail/', views.ProfileinfoView, name = 'profiledetail'),
    path('calendar_app/',include('calendar_app.urls',namespace='calendar_app')),
    path('post_app/', include('post_app.urls', namespace='post_app')),
    path('group/', include('group.urls', namespace='group')),
    path('updateprofile/', views.UpdateProfile, name = 'updateprofile'),
    path('passwordreset/', auth_views.PasswordResetView.as_view(template_name = 'passwordreset.html'), name = 'password_reset'),
    path('passwordreset_done/', auth_views.PasswordResetDoneView.as_view(template_name = 'passwordreset_done.html'), name = 'password_reset_done'),
    path('passwordreset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'passwordreset_confirm.html'), name = 'password_reset_confirm'),
    path('passwordreset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'passwordreset_complete.html'), name = 'password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

group/urls.py
from django.urls import path
from . import views

app_name = 'group'

urlpatterns = [
     path('groupdetail/<int:pk>/', views.GroupDetail, name = 'groupdetail'),
     path('creategroup/', views.CreateGroup, name ='creategroup'),
     path('updategroup/<int:pk>/', views.UpdateGroup, name = 'updategroup'),
     path('deletegroup/<int:pk>/', views.DeleteGroup, name = 'deletegroup'),
     path('joingroup/<int:pk>/', views.JoinGroup, name = 'joingroup'),
     path('leavegroup/<int:pk>/', views.LeaveGroup, name = 'leavegroup'),
     path('kick_out/<int:group_pk>/<int:pk>/', views.Kick_out, name = 'kick_out')
]

post_app/urls.py
from django.urls import path
from . import views

app_name = 'post_app'


# // Remember the pk defined here for "post" is not a pk for the post, it is for
# the particular event's pk for that post

urlpatterns = [
    path('<int:pk>/', views.PostView, name='post'),
    path('createpost/<int:pk>', views.CreatePost, name="createpost"),
    path('updatepost/<int:pk>/', views.UpdatePost, name='updatepost'),
    path('deletepost/<int:pk>/', views.DeletePost, name='deletepost'),
]

templates/guidance.html
{% extends 'index.html' %}
{% block content3 %}

<div class="container">
  <div class="jumbotron guide">
    <h3>Guidance to use this Event Scheduler Application</h3><br>
    <h5>This is an event management application. Here you can use this as a calendar</h5>
  </div>
  <div class="jumbotron guide">
    <ul>
      <li>At first  if you want to know some events then just click on <h7>All Events</h7> in <h7>Home</h7> page </li>
      <li>the creator simply share the particular event's <h7>URL</h7> from the <h7>ALL Event</h7> page </li>
      <li>Now <h7>Register</h7> to this application first and then <h7>Login</h7> </li>
      <li>By <h7>Login</h7> ,The app directly jump you to the <h7>calendar</h7>'s Home page </li>
      <li> At the top of the page (In Navbar), there is a <h7>schedule your event</h7> section to create your <h7>Events</h7> </li>
      <li>By creating the <h7>Event</h7> the app will drop you to the <h7>Event Detail</h7> page you have created! </li>
      <li>By clicking on <h7>Schedule Your Event</h7> the app will drop you to the <h7>Calendar</h7> of the recent month where you can toggle <h7>Next</h7> and <h7>Previous</h7> button to jump to the month </li>
      <li>From the Calendar also you can click on the particular event to see the details about the event and also <h7>Join</h7> and <h7>Leave</h7> the particular event as well! </li>
      <li>Whatever you have scheduled your event get appeared in the calendar </li>
      <li>By <h7>LogIn</h7> you can see click on <h7>post</h7> to see your <h7>Events</h7> post you are member of, If not then you have to either create a <h7>Event</h7> or <h7>Join</h7> a <<h7>Existing Event</h7> to see the <h7>Post</h7> of that event </li>
      <li>Only the admin or the Creator of the event can <h7>Update</h7> or <h7>Delete</h7> the event </li>
      <li>likewise you can also click on <h7>Group</h7> button to see the groups you are member of, if not then <h7>Create</h7> or <h7>Join</h7> the particular group </li>
      <li>The creator has more flexibility to handle the event indeed the creator can also <h7>Kick Out</h7> any members of that event </li>
    </ul>
    <h4>Explore the application!</h4>
    Thanks
  </div>



</div>
{% endblock %}

templates/home.html
<!DOCTYPE html> {% load static %}
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Inline+Text:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/master1.css' %}">
</head>

<body>

    <nav class="navbar navbar-light navbar-expand-lg bg-light">
        <div class="">
            <a href="/" class="navbar-brand"><i class="fas fa-house-user home"></i></a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar3">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="navbar-collapse collapse nvbar" id="collapsingNavbar3">
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav nav2">
                <div class="dropdown dropright nav31">
                    <button class="btn btn-info dropdown-toggle bn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              All Event
           </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <ul class="post">
                            <h6>All Events, You can join the Events!</h6>
                            {% if all_ev %} {% for event in all_ev %}
                            <li> <a href="{% url 'calendar_app:eventinfo' pk=event.id %}"> {{ event.title }}</a> </li>
                            {% endfor %} {% else %}
                            <li>No any Event exists! Go to create new one.</li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <div class="dropdown dropright nav31">
                    <button class="btn btn-info dropdown-toggle bn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                 All Groups
              </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <ul class="post">
                            <h6>All Groups, You can join the Groups!</h6>
                            {% if all_gr %} {% for group in all_gr %}
                            <li> <a href="{% url 'group:groupdetail' pk=group.id %}"> {{ group.group_name }}</a> </li>
                            {% endfor %} {% else %}
                            <li>No any Group exists! Go to create new one.</li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </ul>
            {% endif %}
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                <li>
                    <h4>
                        <a class="nav-link Schedule" href="{% url 'calendar_app:eventlist' %}"> <i class="far fa-calendar-alt"></i> Schedule Your Event</a>
                    </h4>
                </li>
                {% else %}
                <li>
                    <h4>
                        <a class="nav-link Schedule"> <i class="far fa-calendar-alt"></i> Event Scheduler App</a>
                    </h4>
                </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav nav2">
                {% if user.is_authenticated %}
                <div class="bn">
                    <a class="btn btn-info" href="{% url 'group:creategroup' %}"><i class="fas fa-plus-circle"></i>  Create Group</a>
                </div>
                <div class="dropdown dropleft nav31">
                    <button class="btn btn-info dropdown-toggle bn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Post
             </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <ul class="post">
                            <h6>Create a post or visit your existing post for Your Events</h6>
                            {% if events %} {% for event in events %}
                            <li> <a href="{% url 'post_app:post' pk=event.id %}"> {{ event.title }}</a> </li>
                            {% endfor %} {% else %}
                            <li>You have no any events, please create an event or join other events! Click
                                <h5>Schedule Your Event</h5> on the navbar</li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <div class="dropdown dropleft nav32">
                    <button class="btn btn-info dropdown-toggle bn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Group
               </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <ul class="post">
                            <h6>Choose Your Existing Group</h6>
                            {% if list %} {% for group in list %}
                            <li><a href="{% url 'group:groupdetail' pk=group.id %}">{{ group }}</a></li> <br> {% endfor %} {% else %}
                            <li>You have no any groups, please create a group or join other groups! Click
                                <h5>Create Group</h5> on the navbar</li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <div class="">
                    <h3> <a class="btn btn-outline-success user" href="{% url 'profiledetail' %}"><i class="fas fa-user"></i></a></h3>
                </div>
                <div class="">
                    <h3> <a onclick = "checker()" class="btn btn-outline-success logout" href="{% url 'calendar_app:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a></h3>
                </div>
                <script>
                    function checker(){
                        var result = confirm('Are you sure?');
                        if (result == false){
                            event.preventDefault();
                        }
                    }
                </script>
                {% else %}
                <div class="dropdown dropleft">
                    <button class="btn btn-info dropdown-toggle bn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               All Events
            </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <ul class="post">
                            {% if can_see_event %} {% for event in visit_events %}
                            <li> <a href="{% url 'visitevent' pk=event.id %}"> {{ event.title }}</a> </li>
                            {% endfor %} {% else %}
                            <li> Please go to the home page and then click
                                <h6>All Events!</h6>to see the active events </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <li class="nav-item">
                    <a class="btn btn-outline-success login" href="{% url 'calendar_app:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-success signin" href="{% url 'calendar_app:signin' %}">Signin</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% include 'calendar_app/message.html' %} {% block content2 %} {% endblock %}
    <br> {% block content %} {% endblock %}
    <div class="container c1">
        <div class="jumbotron j1">
            <div class="guider">
                <h6>For Better experience/Interface use in Desktop Mode</h6>
                <a href="{% url 'view' %}" class="navbar-brand btn btn-info">How to use</a>
            </div>
            <img src="{% static 'Developer.jpg' %}" width="450">
        </div>
        <div class="jumbotron j2">
            <h1> About </h1>
            <p>The best way to explore or to ameliorate yourself is to connect with the best environment,But if you are searching for that environment then u can't find it indeed it is not even exist but you can create it. That's what the semblance of my
                perception looks like : "Do not search for the best but make the things best by yourself" </p>
            <u>
             <li>Email : prernapk2001@gmail.com / 2020ugmm064@nitjsr.ac.in</li><br>
             <li>Education : National Institute of Technology Jamshedpur </li><br>
             <li>Phone : +91-7209864690 / +91-7321013968</li>
           </u>
        </div>
    </div>
    <div class="container c2">
        <div class="jumbotron">
            <div class="j3">
                <h2>Contact</h2>
            </div>
            <div>
                <a href="https://www.facebook.com/profile.php?id=100056026988248"><i class="fab fa-facebook-square facebook"></i></a>
                <a href="https://twitter.com/Preekp12?t=1gnP5s5r0KIeruWdlA9sGg&s=09"><i class="fab fa-twitter-square twitter"></i></a>
                <a href="https://github.com/prernapk064"><i class="fab fa-github-square github"></i></a>
                <a href="https://www.linkedin.com/in/prerna-pan-a178ba202"><i class="fab fa-linkedin linkedin"></i></a>
            </div>
        </div>
    </div>
    <!-- //Font Awsome -->
    <script src="https://kit.fontawesome.com/b25f0b70e4.js" crossorigin="anonymous"></script>

    <!-- For j-query -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- // Bootstrap4 // -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- // Font Google // -->
    <link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Inline+Text:wght@900&display=swap" rel="stylesheet">
    <!-- // Static File // -->
    <link rel="stylesheet" href="{% static 'css/master2.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-light navbar-expand-lg bg-light">
      <div class="">
        <a href="/" class="navbar-brand"><i class="fas fa-house-user home"></i></a>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar3">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse nvbar" id="collapsingNavbar3">
        <ul class = "nav navbar-nav nav2">
          <div class="dropdown dropright nav31">
             <button class="btn btn-info dropdown-toggle bn"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                All Event
             </button>
             <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" >
               <ul class="post">
                  <h6>All Events, You can join the Events!</h6>
                  {% if all_ev %}
                      {% for event in all_ev %}
                           <li> <a href="{% url 'calendar_app:eventinfo' pk=event.id %}"> {{ event.title }}</a> </li>
                      {% endfor %}
                  {% else %}
                           <li>No any Event exists! Go to create new one.</li>
                  {% endif %}
                </ul>
              </div>
            </div>
             <div class="dropdown dropright nav31">
                <button class="btn btn-info dropdown-toggle bn"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   All Groups
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" >
                  <ul class="post">
                     <h6>All Groups, You can join the Groups!</h6>
                     {% if all_gr %}
                         {% for group in all_gr %}
                              <li> <a href="{% url 'group:groupdetail' pk=group.id %}"> {{ group.group_name }}</a> </li>
                         {% endfor %}
                     {% else %}
                          <li>No any Group exists! Go to create new one.</li>
                     {% endif %}
                   </ul>
                 </div>
            </div>
         </ul>
          <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
             <li>
               <h4><a class="nav-link Schedule" href="{% url 'calendar_app:eventlist' %}"> <i class="far fa-calendar-alt"></i> Schedule Your Event</a></h4>
             </li>
             {% else %}
             <li>
               <h4><a class="nav-link Schedule"> <i class="far fa-calendar-alt"></i> Event Scheduler App</a></h4>
             </li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav nav2">
            {% if user.is_authenticated %}
            <div class="bn">
              <a class="btn btn-info" href="{% url 'group:creategroup' %}"><i class="fas fa-plus-circle"></i>  Create Group</a>
            </div>
            <div class="dropdown dropleft nav31">
               <button class="btn btn-info dropdown-toggle bn"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Post
               </button>
               <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" >
                 <ul class="post">
                    <h6>Create a post or visit your existing post for Your Events</h6>
                    {% if events %}
                        {% for event in events %}
                             <li> <a href="{% url 'post_app:post' pk=event.id %}"> {{ event.title }}</a> </li>
                        {% endfor %}
                    {% else %}
                             <li>You have no any events, please create an event or join other events! Click <h5>Schedule Your Event</h5> on the navbar</li>
                    {% endif %}
                  </ul>
                </div>
               </div>
               <div class="dropdown dropleft nav32">
                 <button class="btn btn-info dropdown-toggle bn"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Group
                 </button>
                 <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" >
                   <ul class="post">
                      <h6>Choose Your Existing Group</h6>
                      {% if list %}
                         {% for group in list %}
                            <li><a href="{% url 'group:groupdetail' pk=group.id %}">{{ group }}</a></li>  <br>
                         {% endfor %}
                      {% else %}
                      <li>You have no any groups, please create a group or join other groups! Click <h5>Create Group</h5> on the navbar</li>
                      {% endif %}
                    </ul>
                  </div>
              </div>
              <div class="">
                <h3> <a class="btn btn-outline-success user" href="{% url 'profiledetail' %}"><i class="fas fa-user"></i></a></h3>
              </div>
              <div class="">
                <h3> <a  onclick = "checker()" class="btn btn-outline-success logout" href="{% url 'calendar_app:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a></h3>
                {% comment %} wanted to add {% endcomment %}
                {% comment %} <h3> <a class="btn btn-outline-success logout" href="{% url 'calendar_app:confirmlogout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a></h3> {% endcomment %}
              </div>
            {% else %}
             <li class="nav-item">
                <a class="btn btn-outline-success login" href="{% url 'calendar_app:login' %}">Login</a>
             </li>
             <li class="nav-item">
                <a class="btn btn-outline-success signin" href="{% url 'calendar_app:signin' %}">Signin</a>
                
             </li>
             {% endif %}
           </ul>
        </div>
     </nav>
     {% block content3 %}
     {% endblock %}
     {% include 'calendar_app/message.html' %}
     {% block content2 %}
     {% endblock %}
    {% block content %}
    {% endblock %}
    <!-- //Font Awsome -->
    <script src="https://kit.fontawesome.com/b25f0b70e4.js" crossorigin="anonymous"></script>
    <!-- For j-query -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>

templates/passwordreset.html
{% include 'index.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="container-md cont">
      <div class="jumbotron reset">
        <h1> Provide us your email address</h1>
        <p> Make sure that you have already registered your email address </p>
        <form method="POST">
           {% csrf_token %}
           {% bootstrap_form form %}
           <input class="btn btn-info" type="submit" name="" value="Confirm">
        </form>
      </div>
    </div>
{% endblock %}

templates/passwordreset_complete.html
{% include 'index.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="container-md">
      <div class="jumbotron reset">
        <h2>Your new password is formed</h2>
        <h3>Just go ahead and login!</h3><br>
        <h3> <a class="btn btn-info" href="{% url 'HOME' %}"> Jump to HOME </a> </h3>
        {% block page %}
        {% endblock %}
      </div>
    </div>
{% endblock %}

templates/passwordreset_confirm.html
{% include 'index.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="container-md">
      <div class="jumbotron">
        <div class="reset">
          <h1> Reset your password</h1>
        </div>
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="reset">
            <input class="btn btn-info" type="submit" name="" value="Reset">
          </div>
        </form>
        {% block page %}
        {% endblock %}
      </div>
    </div>
{% endblock %}

templates/passwordreset_done.html
{% include 'index.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="container-md">
      <div class="jumbotron reset1">
        <ul>
          <li><h2>We have emailed you a notification about to reset password and some link are also given!</h2></li><br>
          <li><h3>Just go through the link from the mail account</h3></li><br>
          <li><h4>If somehow you can't recieve an email , please make sure that the entered email-id is registered or valid or also check your spam folder</h4></li>
        </ul>
      </div>
    </div>
{% endblock %}

templates/profiledetail.html
{% extends 'index.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container-sm">
      <div class="jumbotron p">
        <h2 id='h2'>Profile</h2>
        <div class="profl">
          <div class="img">
             <img src="{{ profile.profile_pic.url }}" width="250">
          </div>
          <div class="prof">
             <h5> User : {{ profile }} </h5><br>
             <h5> Profession : {{ profile.profession }} </h5><br>
             <h5> Email : {{ user.email }} </h5><br>
             <h5> contact : {{ profile.contact }} </h5>
          </div>
        </div>
        <h2><a class="btn btn-info" href="{% url 'updateprofile' %}">Update</a></h2>
      </div>
</div>
{% endblock %}

templates/t.html
<table border="0" cellpadding="0" cellspacing="0" class="month">
    <tr><td class="mon">15</td><td class="tue">16</td><td class="wed">17</td><td class="thu">18</td><td class="fri">19</td><td class="sat">20</td><td class="sun">21</td></tr>       
    <tr><td class="mon">22<div class="t"><li><a style="color:#294047;background-color:#ede6e6" href="/calendar_app/eventdetail/1/" class="added">testing<br> at 10:26 pm</a></li></div></td><td class="tue">23<div class="t"><li><a style="color:#294047;background-color:#ede6e6" href="/calendar_app/eventdetail/2/" class="added">Inter NIT tournament<br> at 01:34 pm</a></li></div></td><td class="wed">24</td><td class="thu">25</td><td class="fri">26</td><td class="sat">27</td><td class="sun">28</td></tr>
    <tr><td class="mon">29</td><td class="tue">30</td><td class="wed">31</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td></tr></table>

templates/thanks.html
{% extends 'home.html' %}
{% block content %}
<div class="container">
  <div class="jumbotron j4">
    <h2>VISIT AGAIN !</h2>
  </div>
</div>
{% endblock %}

templates/updateprofile.html
{% extends 'index.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <div class="jumbotron update">
        <h1>Update Profile</h1>
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input class="btn btn-info" type="submit" name="" value="Update">
        </form>
  </div>
</div>
{% endblock %}

templates/visitevent.html
{% extends "index.html" %}
{% block content %}
<div class="container">
  <div class="dm">
    <div class="jumbotron detail">
      <ul>
        <li>Event Name   :   {{ eve.title }}</li><br>
        <li>Event Creator   :   @{{ eve.creator }}</li><br>
        <li>Created at   :   {{ eve.created_at }}</li><br>
        <li>Start at   :   {{ eve.start_at }}</li><br>
        <li>End at   :   {{eve.end_at }}</li><br>
      </ul>
    </div>
   <div class="jumbotron member">
     <h2>Members</h2><br>
      {% for member in members %}
        <div class="kick_out">
            <li> {{ member }}</li>
        </div><br>
      {% endfor %}
    </div>
  </div>
  <div class="jumbotron about">
    <h2>About this event</h2>
    {{ eve.about }} <br><br>
  </div>
</div>
<div class="container psts">
   <button type="button " class="btn btn-info">
     Total Post for this event <span class="badge badge-light">{{ all_posts.count }}</span>
   </button>
   <ol>
     {%  for post in all_posts %}
     <li>
       <div class="jumbotron pst">
          <div class="post1">
              {{ post.count }}
              <h5> {{ post.post }} </h5><br>
          </div>
          <div class="post2">
              <h3>Posted At</h3>
              <h5> {{ post.post_at }} </h5>
           </div>
        </div>
      </li>
     {% endfor %}
   </ol>
</div>
{% endblock %}