calendar_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import signup
from . import views

app_name = 'calendar_app'


urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name = 'calendar_app/login.html'),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(),name = 'logout'),
    path('signin/',signup.Signin,name = 'signin'),
    path('',views.Eventdisplay,name = 'eventlist'),
    path('createevent/',views.CreateEvent, name = "createevent"),
    path('eventdetail/<int:pk>/',views.EventInfo, name='eventinfo'),
    path('updateevent/<int:pk>/', views.UpdateEvent, name = 'updateevent'),
    path('delete_event/<int:pk>/', views.DeleteEvent, name = 'deleteevent'),
    path('joinevent/<int:pk>/', views.JoinEvent, name = 'joinevent'),
    path('leaveevent/<int:pk>/', views.LeaveEvent, name = 'leaveevent'),
    path('kick_out/<int:event_pk>/<int:pk>/', views.Kick_out, name = 'kick_out'),
    path('memberprofile/<int:pk>/', views.Memberprofile, name = 'memberprofile'), 
    
]

calendar_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import ProfileinfoView
from django.contrib.auth import views as auth_views
from . import views
from calendar_app import signup

urlpatterns = [
    path('',views.Home,name = 'HOME'),
    path('index/',views.Index,name = 'view'),
    path('visitevent/<int:pk>/', views.VisitEvent, name = 'visitevent'),
    #use of as_view() only when you are using any class in views.py else use it normally
    path('thanks/',views.ThanksView.as_view(),name = 'THANKS'),
    path('admin/', admin.site.urls),
    path('profiledetail/', views.ProfileinfoView, name = 'profiledetail'),
    path('calendar_app/',include('calendar_app.urls',namespace='calendar_app')),
    path('post_app/', include('post_app.urls', namespace='post_app')),
    path('group/', include('group.urls', namespace='group')),
    path('updateprofile/', views.UpdateProfile, name = 'updateprofile'),
    path('passwordreset/', auth_views.PasswordResetView.as_view(template_name = 'passwordreset.html'), name = 'password_reset'),
    path('passwordreset_done/', auth_views.PasswordResetDoneView.as_view(template_name = 'passwordreset_done.html'), name = 'password_reset_done'),
    path('passwordreset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'passwordreset_confirm.html'), name = 'password_reset_confirm'),
    path('passwordreset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'passwordreset_complete.html'), name = 'password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

group/urls.py
from django.urls import path
from . import views

app_name = 'group'

urlpatterns = [
     path('groupdetail/<int:pk>/', views.GroupDetail, name = 'groupdetail'),
     path('creategroup/', views.CreateGroup, name ='creategroup'),
     path('updategroup/<int:pk>/', views.UpdateGroup, name = 'updategroup'),
     path('deletegroup/<int:pk>/', views.DeleteGroup, name = 'deletegroup'),
     path('joingroup/<int:pk>/', views.JoinGroup, name = 'joingroup'),
     path('leavegroup/<int:pk>/', views.LeaveGroup, name = 'leavegroup'),
     path('kick_out/<int:group_pk>/<int:pk>/', views.Kick_out, name = 'kick_out')
]

calendar_app/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

class Event(models.Model):
    creator = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 100, unique = True , null = False)
    about = models.TextField()
    start_at = models.DateTimeField()
    end_at = models.DateTimeField()
    created_at = models.DateTimeField(default = datetime.now)

    def __str__(self):
        return f'{self.title} conducted by {self.creator}'

    def get_absolute_url(self):
        return reverse('calendar_app:eventinfo', kwargs={"pk":self.pk})

    @property
    def event_url(self):
        return '{}'.format(reverse('calendar_app:eventinfo', kwargs={"pk":self.pk}))


class Profile(models.Model):
    user_name = models.ForeignKey(User, on_delete = models.CASCADE)
    profession = models.TextField(max_length = 300, blank = True, null = False)
    email = models.EmailField(blank = False)
    profile_pic = models.ImageField(upload_to = 'profile', null = True, default = 'default.jpg')
    contact = models.BigIntegerField(null = True, default = '0000000000')

    def __str__(self):
        return f'{"@"}' + f'{self.user_name.username}'

    def get_absolute_url(self):
        return reverse('profiledetail', kwargs={'pk' : self.pk})

class EventMembers(models.Model):
    event = models.ForeignKey(Event, on_delete = models.CASCADE)
    member = models.ForeignKey(User, on_delete = models.CASCADE)

    class Meta:
      unique_together = ['event', 'member']

    def __str__(self):
        return f'{self.member}'

calendar_app/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from . import models
from django import forms
from django.forms import ModelForm , DateInput

User = get_user_model()


class SigninForm(UserCreationForm):
    class Meta:
       model = User
       fields = ['username','email','password1','password2']

class EventForm(ModelForm):
  class Meta:
    model = models.Event
    widgets = {
      'start_at': DateInput(format='%Y-%m-%dT%H:%M', attrs={'type' : 'datetime-local'}),
      'end_at': DateInput(format='%Y-%m-%dT%H:%M', attrs={'type' : 'datetime-local'})
    }
    exclude = ['creator', 'created_at']

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    #super() in multiple inheritance
    self.fields['start_at'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_at'].input_formats = ('%Y-%m-%dT%H:%M',)

class ProfileForm(ModelForm):
    class Meta:
        model = models.Profile
        fields = ['profession', 'email', 'profile_pic', 'contact']

calendar_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from calendar_app.models import Event, EventMembers, Profile
from datetime import datetime,date, timedelta
from django.contrib.auth.models import User
from calendar import HTMLCalendar
from group.models import *
from calendar_app.forms import SigninForm, EventForm
from django.utils.safestring import mark_safe
from django.utils.html import format_html
from datetime import datetime
from django.contrib.auth.decorators import login_required
from collections import defaultdict
from django.contrib import messages
from .calendar import Calendar
from calendar_pro.views import *
import calendar
# Create your views here.



def current_date(current):
     if current:
         year, month = current.split('-')
         return datetime(year = int(year), month = int(month), day = 1)
     return datetime.today()

def Next(day):
    total_days = calendar.monthrange(day.year,day.month)[1]
    day = day.replace(day = total_days)
    # day -> object of datetime, can u add something on any object + 1, istead of this, you can do -> object + object
    # timedelta is basically used for doing Arithmetic operation in datetime object
    next_month = day + timedelta(days=1)
    print("next-month",next_month)
    
    month_year ="month_year=" + str(next_month.year) + '-' + str(next_month.month)
    print(month_year)
    return month_year

def Previous(day):
    day = day.replace(day = 1)
    previous_month = day - timedelta(days=1)
    month_year = "month_year=" + str(previous_month.year) + '-' + str(previous_month.month)
    return month_year

def get_context_data(request):
    current = current_date(request.GET.get("month_year",None))
    print("current-month",current)
   
    html = Calendar(current.year, current.month)
    html_cal = html.Active_day()
    
    current_month_events = Event.objects.filter(start_at__month = current.month)
    events = []
    for event in Member_or_Not(request.user):
        for current_mon_ev in current_month_events:
               if event.start_at == current_mon_ev.start_at:
                      events.append(event)

    content = {
    'next' : Next(current), #month_year=2022-8
    'previous' :Previous(current),
    'calendar' : format_html(html_cal),
    'events' : events,
    'list' : Group_Mem(request.user),
    'today' : datetime.today(),
    'current_month_events' : current_month_events,
    'all_ev' : AllEvents("give"),
    'all_gr' : AllGroups("give")
    }
    return content


@login_required
def Eventdisplay(request):
    print(request.GET)
    context = get_context_data(request)
    return render(request, 'calendar_app/eventlist.html', context)


# // Here above, the format_html or mark_safe are same kind of method which makes the format as it is
# // like here if we not use the format_html(html_cal) then in web page the it shows the content in html_cal
# not the output view (as html_cal here is a html code in text format so to use it in web we have to use format_html or mark_safe)

@login_required
def CreateEvent(request):
    form = EventForm()
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            creator = request.user
            title = form.cleaned_data['title']
            about = form.cleaned_data['about']
            start_at = form.cleaned_data['start_at']
            end_at = form.cleaned_data['end_at']
            about = form.cleaned_data['about']
            obj = Event(creator = creator,title = title, start_at = start_at, end_at = end_at, about = about)
            obj.save()
            messages.success(request, "Your event has successfully created!")
            EventMembers.objects.create(event = obj, member = request.user )
            return redirect(obj)
    context = {
    'form' : form,
    'events' : Member_or_Not(request.user),
    'list' : Group_Mem(request.user),
    'all_ev' : AllEvents("give"),
    'all_gr' : AllGroups("give")
    }
    return render(request, 'calendar_app/event_form.html',context)

def EventInfo(request,pk):
    event = get_object_or_404(Event, pk = pk)
    members = EventMembers.objects.filter(event = event)
    context = {
    'event' : event,
    'members' : members,
    'events' : Member_or_Not(request.user),
    'list' : Group_Mem(request.user),
    'all_ev' : AllEvents("give"),
    'all_gr' : AllGroups("give")
    }
    return render(request, 'calendar_app/event_detail.html', context)

def UpdateEvent(request, pk):
    event = Event.objects.get(id = pk)
    if request.user == event.creator:
        event_form = EventForm(instance = event)
        if request.method == 'POST':
            event_form = EventForm(request.POST, instance = event)
            if event_form.is_valid():
                 event_form.save()
                 messages.success(request, "Your event is updated successfully!")
                 return redirect(Event.objects.get(id=pk))
        return render(request, 'calendar_app/update_event.html', {'form' : event_form , 'events' : Event.objects.all()})
    else:
        messages.warning(request, f"You are not the creator of : {event.title} event so you can't update!")
    context = {
    'event' : event,
    'members' : EventMembers.objects.filter(event = event),
    'events' : Member_or_Not(request.user),
    'list' : Group_Mem(request.user),
    'all_ev' : AllEvents("give"),
    'all_gr' : AllGroups("give")
    }
    return render(request, 'calendar_app/event_detail.html', context)


def DeleteEvent(request, pk):

    event = get_object_or_404(Event, pk = pk)
    if request.user == event.creator:
        event.delete()
        messages.success(request, "You have deleted this event successfully!")
        return redirect('/')
    else:
        messages.success(request, f"You are not the creator of : {event.title} event, so you can't delete!")

    return redirect('/')

# /////////////////////// EventMembers /////////////////////////

def JoinEvent(request, pk):
    event = get_object_or_404(Event, id = pk)
    eventmember = EventMembers(event = event, member = request.user)
    if Event.objects.get(id = pk).creator == request.user:
        messages.warning(request, "Since you are the creator of this event so you are already the member of this group!")
    try:
        eventmember.save()
        messages.success(request, 'You successfully joined this event!')
    except:
        pass
    context = {
    'event' : event,
    'members' : EventMembers.objects.filter(event = event),
    'events' : Member_or_Not(request.user),
    'list' : Group_Mem(request.user),
    'all_ev' : AllEvents("give"),
    'all_gr' : AllGroups("give")
    }
    return render(request,'calendar_app/event_detail.html',context)

def LeaveEvent(request, pk):
    event = get_object_or_404(Event, id = pk)
    eventmember = EventMembers.objects.filter(event = event, member = request.user)
    # // Mind it the queryset is always in the form of iterator
    # // so we are doing this to get that particular objects which is going to leave this event
    try:
       if Event.objects.get(id = pk).creator == request.user:
            messages.warning(request, "You can't leave this event as you are the creator, You have to delete this event instead!")
       elif request.user == eventmember[0].member:
            eventmember.delete()
            messages.success(request, 'You leaved this event successfully!')
    except:
        pass

    context = {
    'event' : event,
    'members' : EventMembers.objects.filter(event = event),
    'events' : Member_or_Not(request.user),
    'list' : Group_Mem(request.user),
    'all_ev' : AllEvents("give"),
    'all_gr' : AllGroups("give")
    }
    return render(request, 'calendar_app/event_detail.html', context)

def Kick_out(request,event_pk,pk):
    event = Event.objects.get(id=event_pk)
    if event.creator.username == request.user.username:
        if request.user.username == User.objects.get(id=pk).username:
            messages.warning(request, "Since you are the creator so you can't kick Yourself out, instead you have to delete this event!")
        else:
            kick_me = EventMembers.objects.filter(event__id = event_pk, member__id = pk )
            kicked_to = kick_me[0].member.username
            kick_me.delete()
            messages.warning(request, f"You have successfully kicked {kicked_to}")
    else:
        messages.warning(request, "You are not the creator of this event so you can't kick_out the member")
    context = {
    'event' : get_object_or_404(Event, pk = event_pk),
    'members' : EventMembers.objects.filter(event__id=event_pk),
    'events' : Member_or_Not(request.user),
    'list' : Group_Mem(request.user),
    'all_ev' : AllEvents("give"),
    'all_gr' : AllGroups("give")
    }
    return render(request,'calendar_app/event_detail.html', context)


# ///////////////////////////// Members Profile ///////////////////////////////////////////////

def Memberprofile(request, pk):
    instant_user =  User.objects.get(id=pk)
    # instant_profile = Profile.objects.get(id = instant_user.id)
                                                                # ////Since i have to grab Profile of the user so i have to do
                                                                # /// Profile.objects.get(user_name = instant_user.id) not
                                                                # ///Profile.objects.get(id = instant_user.id)
    member_profile = Profile.objects.get(user_name = instant_user.id)
                                                                # ///Now here we have filter method to get all the event related to that mamber
                                                                # ///If we use get instead of filter then mind it get only gives you a single object
    active_events = Event.objects.filter(creator = instant_user.id)
    context = {
    'member_pro' : member_profile,
    'memberevents' : active_events,

calendar_app/templates/calendar_app/delete_event.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"
    <title></title>
  </head>
  <body>
    <div class="container-md">
      <div class="jumbotron">
        <h1> Delete your event</h1>
        <form method="post">
          {% csrf_token %}
          <input type="submit" name="" value="Delete">
        </form>
        {% block page %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

calendar_app/templates/calendar_app/event_detail.html
{% extends "index.html" %}
{% block content %}
<div class="container">
  <div class="dm">
    <div class="jumbotron detail">
      <ul>
        <li>Event Name   :   {{ event.title }}</li><br>
        <li>Event Creator   :   @{{ event.creator }}</li><br>
        <li>Created at   :   {{ event.created_at }}</li><br>
        <li>Start at   :   {{ event.start_at }}</li><br>
        <li>End at   :   {{event.end_at }}</li><br>
      </ul>
      <div class="joinleave">
        <h2> <a class="btn btn-info" href="{% url 'calendar_app:joinevent' pk=event.id %}">Join</a></h2>
        <h2> <a class="btn btn-info" href="{% url 'calendar_app:updateevent' pk=event.id %}">Update</a></h2>
        <h2> <a class="btn btn-info" href="{% url 'calendar_app:leaveevent' pk=event.id %}">Leave</a></h2>
      </div>
    </div>
   <div class="jumbotron member">
     <h2>Members</h2><br>
      {% for member in members %}
        <div class="kick_out">
            <li> <a href="{% url 'calendar_app:memberprofile' pk=member.member.id %}">{{ member }}</a></li>
            <h6><a class="btn btn-info" href="{% url 'calendar_app:kick_out' event_pk=event.id pk=member.member.id %}"> Kick_out </a></h6>
        </div><br>
      {% endfor %}
    </div>
  </div>
  <div class="jumbotron about">
    <h2>About this event</h2>
    {{ event.about }} <br><br>
    <a class="btn btn-info" href="{% url 'calendar_app:deleteevent' pk=event.id %}">Delete</a>
  </div>
</div>
{% endblock %}

calendar_app/templates/calendar_app/event_form.html
{% extends 'index.html' %}
{% load bootstrap4 %}
{% block content %}
 <div class="container">
   <div class="jumbotron update">
     <h1> Schedule your event</h1>
     <form method="post">
       {% csrf_token %}
       {% bootstrap_form form %}
       <input class="btn btn-info" type="submit" name="" value="Create">
     </form>
   </div>
 </div>
{% endblock %}

calendar_app/templates/calendar_app/eventlist.html
{% extends 'index.html' %}
{% block content %}
<div class="action">
    <a class="btn btn-info" href="{% url 'calendar_app:eventlist' %}?{{ previous }}"><i class="fas fa-fast-backward"></i> previous</a>
    <a class="btn btn-info" href="{% url 'calendar_app:createevent' %}"><i class="fas fa-plus-circle"></i>  Create Event</a>
    <a class="btn btn-info" href="{% url 'calendar_app:eventlist' %}?{{ next }}"> <i class="fas fa-fast-forward"></i> next </a>
</div>
<div class="container display">
  <div class="jumbotron my_event">
    <h7>My events on this month</h7>
    <ol>
    {% for ev in events %}
         <a href="{% url 'calendar_app:eventinfo' pk=ev.id %}" ><li>{{ ev.title }}</li></a><br>
    {% endfor %}
    </ol>
  </div>
   <div class="jumbotron list">
     <h4>Today : {{ today }} </h4>
     {{ calendar }}
   </div>
   <div class="jumbotron todays_event">
     <h7>Events on this month</h7>
     <ol>
     {% for ev in current_month_events %}
          <a href="{% url 'calendar_app:eventinfo' pk=ev.id %}" ><li>{{ ev.title }}</li></a><br>
     {% endfor %}
     </ol>
   </div>
</div>
{% endblock %}

calendar_app/templates/calendar_app/firstupdate.html
{% extends 'index.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <div class="jumbotron update">
        <h1>Update Profile</h1>
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input class="btn btn-info" type="submit" name="" value="Update">
        </form>
  </div>
</div>
{% endblock %}

calendar_app/templates/calendar_app/leaveevent.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"
    <title></title>
  </head>
  <body>
    <div class="container-md">
      <div class="jumbotron">
        <form method="POST">
          {% csrf_token %}
             <input type="submit" name="" value="Leave">
        </form>
      </div>
    </div>
  </body>
</html>

calendar_app/templates/calendar_app/login.html
{% extends 'home.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Login</h1>
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="login">
        <input class="btn btn-info" type="submit" value="login"><br><br>
        <a class="btn btn-info" href="{% url 'password_reset' %}">Forgotten password?</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

calendar_app/templates/calendar_app/memberprofile.html
{% extends 'index.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container-sm active_events">
    <div class="jumbotron p">
      <h2 id='h2'>Profile</h2>
      <div class="profl">
          <div class="img">
            <img src="{{ member_pro.profile_pic.url }}" width="250">
          </div>
          <div class="prof">
            <h5> User : {{ member_pro }} </h5><br>
            <h5> Profession : {{ member_pro.profession }} </h5><br>
            <h5> Email : {{ member_pro.email }} </h5><br>
            <h5> contact : {{ member_pro.contact }} </h5>
          </div>
      </div>
        {% if user.id == instant_user.id %}
            <h2><a class="btn btn-info" href="{% url 'updateprofile' %}">Update</a></h2>
        {% endif %}
    </div>
    <div class="jumbotron q">
        <h2>Events</h2>
        <ol>
          {% for event in memberevents %}
            <h4> <li> {{ event }} </li> </h4> : <h5> at {{ event.start_at}} on {{ event.start_at.date }} to {{ event.end_at}}  </h5>
          {% endfor %}
        </ol>
    </div>
</div>
{% endblock %}

calendar_app/templates/calendar_app/message.html
{% if messages %}
  {% for message in messages %}
    {% if message.tags %}
      <div class= "{{ message.tags }} alert alert-info" role="alert">
        {{ message }}
      </div>
    {% endif %}
  {% endfor %}
{% endif %}

calendar_app/templates/calendar_app/signin.html
{% extends 'home.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Register</h1>
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="login">
        <input type="submit" class="btn btn-info i" value="Register">
      </div>
    </form>
  </div>
</div>
{% endblock %}

calendar_app/templates/calendar_app/update_event.html
{% extends 'index.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <div class="jumbotron update">
      <h1> Sechdule your event</h1>
      <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input class="btn btn-info update" type="submit" value="Update">
      </form>
  </div>
</div>
{% endblock %}

calendar_app/templates/calendar_app/welcome.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"
    <title></title>
  </head>
  <body>
    <div class="container-md">
      <div class="jumbotron">
        <h1> You are going to be the part of this group, Please confirm</h1>
        <form method="POST">
          {% csrf_token %}
          <input type="submit" name="" value="Confirm">
        </form>
      </div>
    </div>
  </body>
</html>